import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="m-0">
      <body className={`${arimo.variable}  antialiased `}>
        <ThemeProvider defaultTheme="light" attribute={"class"}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
